
# No other language is allowed.
language: python

# This defines the path to the interpreter the module is tested against.
# A different script is generated for each PATH.
# A path cannot be a virtual environment.
python:
  - { PATH: "{{Python39}}", VERSION: 3.9, DIST: std, PYINT: python3.9, PYTHONPATH: src }
  
# The test happens in a virtual environment not with the original distribution.
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
# Dependencies to install.
install:
  - $PYINT -m pip install --upgrade pip
  - $PYINT -m pip install --upgrade --no-cache-dir --no-deps --index http://localhost:8067/simple/ jyquickhelper tkinterquickhelper --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install --upgrade --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyrsslocal --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install --upgrade --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyensae --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install -r requirements.txt
  - $PYINT --version
  - $PYINT -m pip uninstall -y pyquickhelper
  - $PYINT -m pip freeze

# Runs before the main script.
before_script:
  - $PYINT setup.py write_version

# The script to run.
# Each row becomes a Jenkins job. pyquickhelper will generate nb(python) * nb(script) jobs to run on Jenkins.
# Steps before_script and after_script are run for every script.
# Variable NAME is added to the Job name on Jenkins in order to distinguish them.
# By default, the timeout for the job (only used in Jenkins) is set to 1200 (20 minutes).
# This means the job will be stop if it produces no output for 20 minutes.
script:
  - { CMD: "$PYINT -u setup.py unittests --covtoken=69193a28-dc79-4a24-98ed-aedf441a8249", NAME: "UT", TIMEOUT: 899 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*SKIP.*\" -g \".*((api)|(pylint)|(gitjs)).*\"", NAME: "UT_SKIP", TIMEOUT: 900 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*api.*\"", NAME: "UT_SKIP_API" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*pylint.*\"", NAME: "UT_SKIP_PYLINT", TIMEOUT: 3000 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*gitjs.*\"", NAME: "UT_SKIP_GITJS", TIMEOUT: 1500 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*LONG.*\"", NAME: "UT_LONG_DOC", TIMEOUT: 900 }

# To run after the script.
after_script:
  - $PYINT -u setup.py bdist_wheel
  - if [ ${VERSION} == "3.9" and ${DIST} != "conda" and ${NAME} == "UT" ] then cp dist/*.whl {{root_path}}/../local_pypi/local_pypi_server fi

# Same as after script.
documentation:
  - if [ ${NAME} == "UT" ] then $PYINT -u setup.py build_sphinx fi
  - if [ ${NAME} == "UT" and ${VERSION} == "3.9" ] then cp -R -f _doc/sphinxdoc/build/html dist/html fi
  - if [ ${NAME} == "UT" and ${VERSION} == "3.9" ] then zip doc.zip -r dist/html fi
