# -*- coding: utf-8 -*-
"""
@file
@brief Title, text depending on language
"""

TITLES = {
    'en': {"blogpost": "blogpost",
           "toc": "Contents",
           "download": "download",
           "by category:": "By category:",
           "by month:": "By month:",
           "page1": "first page",
           "by title:": "By title :",
           "allblogs": "All blog posts",
           "catsmaonths": "All categories and months",
           "more": "post",
           "main": "blog list",
           "main2": "blog main page",
           "main_title": "blog page",
           "glossary": "Glossary",
           "toc0": "Links",
           "toc1": "Information",
           "license": "License",
           "changes": "Changes",
           "FAQ": "FAQ",
           "Magic commands": "Magic commands",
           "In": ">>>",
           "Out": "Out",
           "Out2": "Raw",
           'todo': 'Todo',
           'todo_node': 'Todo',
           'todoext_node': '',
           'mathdef_node': '',
           'blocref_node': '',
           'exref_node': 'Examples',
           'faqref_node': 'FAQ',
           'nbref_node': 'Magic command',
           'original entry': 'original entry',
           'todomes': '(The <<%s>> is located in %s, line %d.)',
           'mathmes': '(<<%s>> : %s, line %d)',
           'brefmes': '(<<%s>> : %s, line %d)',
           'faqmes': '(<<%s>> : %s, line %d)',
           'nbmes': '(<<%s>> : %s, line %d)',
           'exmes': '(<<%s>> : %s, line %d)',
           'blog_entry': 'The original entry is located in <<%s>>, line %d and can be found ',
           'cmdmes': '(<<%s>> : %s, line %d)',
           },
    'fr': {"blogpost": "article",
           "toc": "Contenu",
           "download": "télécharger",
           "by category:": "Par catégorie :",
           "by month:": "Par mois :",
           "page1": "première page",
           "by title:": "Par titre :",
           "allblogs": "Tous les articles de blog",
           "catsmaonths": "Catégories et mois",
           "more": "article",
           "main": "liste d'articles du blog",
           "main2": "page principale du blog",
           "main_title": "page de blog",
           "glossary": "Glossaire",
           "toc0": "Liens",
           "toc1": "Information",
           "license": "Licence",
           "changes": "Changements",
           "FAQ": "FAQ",
           "Magic commands": "Commandes magiques",
           "In": ">>>",
           "Out": "Sortie",
           "Out2": "Sortie brute",
           'todo': 'A faire',
           'todo_node': 'A faire',
           'todoext_node': '',
           'mathdef_node': '',
           'blocref_node': '',
           'exref_node': 'Exemples',
           'faqref_node': 'FAQ',
           'nbref_node': 'Commande magique',
           'original entry': 'source',
           'todomes': '(<<%s>> : %s, ligne %d)',
           'mathmes': '(<<%s>> : %s, ligne %d)',
           'brefmes': '(<<%s>> : %s, ligne %d)',
           'faqmes': '(<<%s>> : %s, ligne %d)',
           'nbmes': '(<<%s>> : %s, ligne %d)',
           'exmes': '(<<%s>> : %s, ligne %d)',
           'blog_entry': 'Source <<%s>>, line %d and can be found ',
           'cmdmes': '(<<%s>> : %s, line %d)',
           }
}
