# -*- coding: utf-8 -*-
"""
@file
@brief Title, text depending on language
"""

TITLES = {
    'en': {"blogpost": "blogpost",
           "toc": "Contents",
           "download": "download",
           "by category:": "By category:",
           "by month:": "By month:",
           "page1": "first page",
           "by title:": "By title :",
           "allblogs": "All blog posts",
           "catsmaonths": "All categories and months",
           "more": "post",
           "main": "blog home",
           "main_title": "blog page",
           "glossary": "Glossary",
           "toc0": "Links",
           "toc1": "Information",
           "license": "License",
           "changes": "Changes",
           "FAQ": "FAQ",
           "Magic commands": "Magic commands",
           "In": "In",
           "Out": "Out",
           "Out2": "Raw",
           'todo': 'Todo',
           'todo_node': 'Todo',
           'todoext_node': '',
           },
    'fr': {"blogpost": "article",
           "toc": "Contenu",
           "download": "télécharger",
           "by category:": "Par catégorie :",
           "by month:": "Par mois :",
           "page1": "première page",
           "by title:": "Par titre :",
           "allblogs": "Tous les articles de blog",
           "catsmaonths": "Catégories et mois",
           "more": "article",
           "main": "page principale du blog",
           "main_title": "page de blog",
           "glossary": "Glossaire",
           "toc0": "Liens",
           "toc1": "Information",
           "license": "Licence",
           "changes": "Changements",
           "FAQ": "FAQ",
           "Magic commands": "Commandes magiques",
           "In": "Code",
           "Out": "Sortie",
           "Out2": "Sortie brute",
           'todo': 'A faire',
           'todo_node': 'A faire',
           'todoext_node': '',
           }
}
